# Generated by Django 5.0.4 on 2024-04-15 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('answers1', models.CharField(max_length=100)),
                ('answers2', models.CharField(max_length=100)),
                ('answers3', models.CharField(max_length=100)),
                ('answers4', models.CharField(max_length=100)),
                ('answers5', models.CharField(max_length=100)),
                ('answers6', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(choices=[('A)', 'A)'), ('B)', 'B)'), ('C)', 'C)'), ('D)', 'D)')], max_length=3)),
                ('category', models.CharField(choices=[('Dialog', 'Dialog'), ('Grammar', 'Grammar'), ('Reading', 'Reading')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_test', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])], verbose_name='Select audiofile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dialogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursequestion')),
            ],
        ),
    ]
